version: "3.0"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: php -S 0.0.0.0:8000 -t /app/web
    ports:
    - "8001:8000"
    volumes:
    - .:/app

  composer:
    restart: 'no'
    image: composer
    command: install
    volumes:
    - .:/app